apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wbssecret
  namespace: kube-system
spec:
  dnsNames:
  - vk-mutator.kube-system.svc
  - vk-mutator.kube-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: wbssecret
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vk-mutator
  annotations:
    cert-manager.io/inject-ca-from: kube-system/wbssecret
webhooks:
  - clientConfig:
      service:
        name: vk-mutator
        namespace: kube-system
        path: /mutate
    failurePolicy: Fail
    name: vk-mutator.kube-system.svc
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    admissionReviewVersions: 
      - v1
      - v1beta
---
apiVersion: v1
data:
  cert.pem: ${cert}
  key.pem: ${key}
kind: Secret
metadata:
  name: wbssecret
  namespace: kube-system
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vk-mutator
  name: vk-mutator
  namespace: kube-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: vk-mutator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vk-mutator
  name: vk-webhook
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: vk-mutator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vk-mutator
    spec:
      containers:
        - args:
            - --tlscert=/root/tls.crt
            - --tlskey=/root/tls.key
            - --port=443
            - --v=6
          image: registry.cn-shanghai.aliyuncs.com/kyligence/virtual-webhook:v0.1.1-24-g2bd91c26b8c98c
          imagePullPolicy: Always
          name: webhook
          ports:
            - containerPort: 443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root
              name: wbssecret
      dnsPolicy: ClusterFirst
      serviceAccount: virtual-kubelet
      volumes:
        - name: wbssecret
          secret:
            defaultMode: 420
            items:
              - key: tls.key
                path: tls.key
              - key: tls.crt
                path: tls.crt
            secretName: wbssecret
